# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170701_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.CharField(max_length=250, verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='account',
            name='url',
            field=models.CharField(max_length=75, verbose_name='google+ page'),
        ),
    ]
