# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('accounts', '0003_auto_20170717_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('code', models.CharField(max_length=32, verbose_name='secret code')),
            ],
            bases=('auth.group',),
        ),
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='account_set', related_query_name='account', to='accounts.Group', verbose_name='groups'),
        ),
    ]
