# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170914_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('staff', 'Has access to the admin site'),)},
        ),
    ]
